
services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: siemens_django
    container_name: siemens_django
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=siemens.settings
    command: python manage.py runserver 0.0.0.0:8000